# 数据库 配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: 54shaohan.
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  grpc:
    enable: true
    port: 6666
  session:
    store-type: redis

server:
  port: 8081
  servlet:
    session:
      timeout: 30d