# 数据库 配置
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/user
    username: root
    password: anoyi.com
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  grpc:
    enable: true
    port: 6666
  session:
    store-type: redis
  application:
    name: server-user

server:
  servlet:
    session:
      timeout: 30d